### ISSUE TITLE
Vivado cannot program bit file correctly if the board contains PS core

### ISSUE THREAD

**Issue by ggangliu** [enjoy-digital/litex#1231]
Hi,
I am using a board (zynq7010) which has a PS core and PL core. When programming bit file, JTAG only try to program the first device, but the first device is the ARM core (PS), so cause programming failed. I have checked the related source, I found that the default value of device is 0, I guess this is the reason why JTAG only try the first device. Then changed it to 1, I can program PL successfully. I am not sure if this is a bug, hope you aware of this, thanks.

https://github.com/enjoy-digital/litex/blob/d37ef60e70bd0ce8d28079143b6859d8b928395e/litex/build/xilinx/programmer.py#L141

https://github.com/enjoy-digital/litex/blob/d37ef60e70bd0ce8d28079143b6859d8b928395e/litex/build/xilinx/programmer.py#L157

**Comment by tcal-x** [comment]
Hi @ggangliu , I think `device=0` makes sense as the default here, since that is the usual case.   For boards like Arty Z7 that have a Zynq with PS and PL, you can override the default in the `targets/<board>.py` file:
```
prog.load_bitstream(os.path.join(builder.gateware_dir, soc.build_name + ".bit"), device=1)
```
E.g.  https://github.com/litex-hub/litex-boards/blob/master/litex_boards/targets/digilent_arty_z7.py#L131

**Comment by ggangliu** [comment]
Really thanks @tcal-x. This is the right place. I need much more time to study this framework.
