### ISSUE TITLE
License update makes LiteX non-free

### ISSUE THREAD

**Issue by robtaylor** [enjoy-digital/litex#1514]
The recent updates to the license make LiteX non-free with respect to the OSI definition.
Also these additions mean that corporate legal teams would not accept the usage of LiteX.

I don't know if this is an intended consequence, and if so, its a bug.

I'd also check that all license holders agree with the license change if this is intended, as this is now a narrower license than BSD 2-Clause.

```
Conditions: The project is shared with a permissive BSD 2-Clause License and we
are encouraged to continue sharing it this way thanks to the awesome community
and clients willing to support the project!

To be able to continue doing so, in addition of the BSD 2-Clause License conditions,
we are expecting users to behave with integrity:
- Users making useful use of the project have to be coherent in their behaviour
on social networks.
- Clients using it for commercial use and with unpaid invoices (due to bankruptcy,
liquidation or dissagrements) are not allowed to use/re-integrate post-conflict
developments unless they want to discuss/regularize the situation.
```

**Comment by enjoy-digital** [comment]
Fixed with https://github.com/enjoy-digital/litex/commit/db87fa1a7f91757b52be9d2740fee75906f0e959, intent was not to change the licensing but just to add some precision on our expectation regarding users/clients' behavior. I moved this to the README.md and rephrased it a bit.

It's sad to have to add such precision since I was expecting this to be implicit and it's clearly the case for 99% of users/clients  playing the game, but it seems to be required for the remaining 1%.

The intent of the project is to share as much development as possible in the LiteX ecosystem and encourage our partners/clients to do the same while putting accents on the advantage of open-sourcing things (benefit from future features, reduce maintenance, contribute a piece and enable others to build upon, etc...) The LiteX ecosystem does not has a private side, we only have private designs build with it for clients and are always trying to convince clients to make non project specific parts open-source (Which is not an easy task). More and more developers/clients/partners are playing the game, which is encouraging since this is not yet a common approach in hardware development.  To be able to continue in this direction and put priority on technology rather than business or just stop sharing some of the development, this precision seems useful.

Thanks for your understanding,

Florent
