### ISSUE TITLE
What generates `ctrl_bus_errors_read`?

### ISSUE THREAD

**Issue by shingarov** [enjoy-digital/litex#1842]
Commit c19c343e introduces a reference to `ctrl_bus_errors_read()`.  What generates it?  I suppose something around `soc/integration/builder.py`?

(I am trying to update Microwatt to latest LiteX but every commit after c19c343e fails to build the libbase).

**Comment by enjoy-digital** [comment]
Hi @shingarov,

sorry for the delay. This function is automatically generated during the build when the LiteX's SoCController is present in the design, which I imagine is not the case in your design. This issue should  have already been fixed with e5e472d469b4aad4593ae23983db4ec7099b50aa that remove the SoCController dependency to build the BIOS.
