### ISSUE TITLE
How to replace csr_map_update / mem_map

### ISSUE THREAD

**Issue by mithro** [enjoy-digital/litex#291]
In the [timvideos/litex-buildenv](https://github.com/timvideos/litex-buildenv) repository a bunch of the targets do the following;

https://github.com/timvideos/litex-buildenv/blob/96ab220b0f60e3d509ca0a66dcfb81676ef294d9/targets/arty/base.py#L105-L127
```python
class BaseSoC(SoCSDRAM):
    csr_peripherals = (
        "spiflash",
        "ddrphy",
        "info",
        "cas",
#        "leds",
#        "rgb_leds",
    )
    csr_map_update(SoCSDRAM.csr_map, csr_peripherals)


    SoCSDRAM.mem_map = {
        "rom":      0x00000000,  # (default shadow @0x80000000)
        "sram":     0x10000000,  # (default shadow @0x90000000)
        "main_ram": 0x40000000,  # (default shadow @0xc0000000)
        "csr":      0x60000000,  # (default shadow @0xe0000000)
    }


    mem_map = {
        "spiflash": 0x20000000,  # (default shadow @0xa0000000)
        "emulator_ram": 0x50000000,  # (default shadow @0xd0000000)
    }
    mem_map.update(SoCSDRAM.mem_map)
```

How should the `csr_map_update` and `mem_map` stuff be updated / replaced for the latest API?

**Comment by enjoy-digital** [comment]
You are now encouraged to use `soc.add_csr()` instead of predefining all CSRs and use `csr_map_update`: https://github.com/enjoy-digital/litex/blob/master/litex/boards/targets/arty.py#L66

For `mem_map`, the `shadow_base` has been removed and we now have `cached` and `io` regions. `shadow_base` was difficult to apprehend and consuming half of the address space.

Example of `io` regions are the `csr` or `ethmac`: https://github.com/enjoy-digital/litex/blob/master/litex/boards/targets/arty.py#L89
