### ISSUE TITLE
add_cpu() with CPUNone raises 'More than one CPU is not supported'

### ISSUE THREAD

**Issue by DurandA** [enjoy-digital/litex#303]
LiteX introduced recent changes preventing the use of `add_cpu()` when a _SoCCore_ is initialized with `cpu_type=None`. This snippet from LiteScope examples demonstrate the issue:
```python
SoCCore.__init__(self, platform, sys_clk_freq,
    cpu_type=None,
    csr_data_width=32,
    with_uart=False,
    ident="Litescope example design", ident_version=True,
    with_timer=False
)

# bridge
self.add_cpu(UARTWishboneBridge(platform.request("serial"),
    sys_clk_freq, baudrate=115200))
```

When setting `cpu_type=None`, the _cpu_ submodule is initialized with `cpu.CPUNone()`:
https://github.com/enjoy-digital/litex/blob/f1714405c321bb8265201d86a336e7cfe8afa470/litex/soc/integration/soc_core.py#L203

While `add_cpu()` checks for the _cpu_ attribute:
https://github.com/enjoy-digital/litex/blob/f1714405c321bb8265201d86a336e7cfe8afa470/litex/soc/integration/soc_core.py#L276-L277

Should `add_cpu()` be an internal method to _SoCCore_ (rename to `_add_cpu()`) or should it check for _CPUNone_?

**Comment by enjoy-digital** [comment]
Thanks @DurandA for reporting and proposed fix. The previous use of "add_cpu" was in fact hacky since the SoC builder was requiring at least a CPU but it was in fact in this case just a Wishbone master.

I just updated the LiteScope examples to use `add_wb_master`: https://github.com/enjoy-digital/litescope/commit/1448b5581901ba54b764f7a78268892ae8f5efff and remove the `add_cpu` method with: https://github.com/enjoy-digital/litex/commit/db4739df81d8738fd82b2dcae694720000e801c1

A `add_cpu` method will only be useful when we'll be supporting building SoCs with multiple CPUs which is not the case actually.
