### ISSUE TITLE
LitePCIeDMA questions

### ISSUE THREAD

**Issue by jimmymagemtek** [enjoy-digital/litex#983]
Hi Sir,

For a PCIe device design and we have two ways of traffic, TX(host to device) & RX(device to host), and two DMA ring buffers(TX, RX):

Is LitePCIeDMAReader class able to detect host's write to the TX ring buffer(DMA) & maintain host's write position of the TX ring buffer(TX: host to device) ?

Is LitePCIeDMAWrite class able to detect host's read to the RX ring buffer(DMA) & maintain host's read position of the RX ring buffer(RX: device to host)?

Not sure that this is an existing feature of a scatter-gather DMA controller. Please advise. Thanks.

**Comment by enjoy-digital** [comment]
Hi @jimmymagemtek,

In LitePCIe, the FPGA is the one maintaining the Scatter-Gather loop indexes and regulating the transfers. The Host is just advertised by separate DMAReader/DMAWriter IRQs of the progress/status on the FPGA and has to ensure that writes are done ahead of FPGA reads (DMA Reader, Host --> FPGA) and reads are done after FPGA writes (DMAWriter, FPGA --> Host).

If you need other precisions, can you open an issue in LitePCIe repository since this is specific to LitePCIe?

Thanks.
